config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "posts#index"
  resources :links
  resources :views, path: :v, only: [:show]
  root "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :views, dependent: :destroy
  scope :recent_first, -> { order(created_at: :desc) }
  # can reuse this, make as a common thing

  validates :url, presence: true

  after_save_commit if: :url_previously_changed? do
    MetadataJob.perform_later(to_param)
  end

  def self.find(id)
    super(ShortCode.decode(id))
  end
  def to_param
    ShortCode.encode(id)
  end

  def domain
    URI(url).host rescue URI::InvalidURIError
  end
end

app/models/metadata.rb
require 'open-uri'

class Metadata
  def self.retrieve_from(url)
    new(URI.open(url))
  rescue StandardError
    new
  end

  def initialize(html=nil)
    @doc = Nokogiri::HTML(html)
  end

  def attributes
    {
      title: title,
      description: description,
      image: image
    }
  end

  def title
    @doc.at_css('title')&.text
  end

  def description
    meta_tag_content "description"
  end

  def image
    meta_tag_content "og:image", name_attribute: :property
  end

  def meta_tag_content(name, name_attribute: :name)
    @doc.at_css("meta[#{name_attribute}='#{name}']")&.attributes&.fetch('content', nil)&.text
  end
end

app/models/short_code.rb
class ShortCode
  ALPHABET = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'.freeze
  BASE = ALPHABET.length

  def self.encode(number)
    return ALPHABET.first if number.zero? || number.nil?
    # to avoid hardcode the "0", ALPHABET may change later
    result = ""

    while number > 0 do
      index = number % BASE
      char = ALPHABET[index]
      result.prepend char
      number = number / BASE
      # result = ALPHABET[number % BASE] + result
      # number = number / BASE
    end

    result
  end

  def self.decode(string)
    number = 0

    string.each_char.with_index do |char, index|
      number = ALPHABET.index(char)  + number * BASE
    end

    number
  end
end

# Base62.encode(1024)
# Base62.decode('gw')

app/models/view.rb
class View < ApplicationRecord
  belongs_to :link, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def set_link
    @link = Link.find params[:id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  def index
    @links = Link.recent_first
    @link ||= Link.new
  end

  def show
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream { render turbo_stream: turbo_stream.prepend("links", @link)}
           # background job done
      end
    else
      index # to make sure not render the nil
      render :index, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @link.update(link_params)
      redirect_to @link
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @link.destroy
    redirect_to root_path, notice: "Link has been successfully deleted."
  end

  private
  def link_params
    params.require(:link).permit(:url)  # only allow the `url` parameter
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_path, alert: "Link not found"
  end
  def show
    @link.views.create(
      ip: request.ip,
      user_agent: request.user_agent,
    ) # anti bot, increase a lot of view

    redirect_to @link.url, allow_other_host: true
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favicon_helper.rb
module FaviconHelper
  def favicon_image_tag(domain, **kwargs)
    image_tag google_favicon_url(domain), **kwargs
  end

  def google_favicon_url(domain)
    "https://www.google.com/s2/favicons?domain=#{domain}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Production -->
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://unpkg.com/tippy.js@6"></script>
  </head>

  <body>
    <main class="prose mx-auto mt-28 px-5">
      <% if alert %>
        <p class="bg-yellow-100 text-yellow-900 text-sm font-medium px-4 py-2 rounded"><%= alert %></p>
      <% end %> <!--      the 1st way to do, straight-->
      <%= tag.p notice, class: "bg-blue-100 text-blue-900 text-sm font-medium px-4 py-2 rounded" if notice%>
      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with model: link, data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"} do |form| %>
  <div class="flex gap-2 items-center" >
    <%= form.url_field :url, required: true, autofocus: true, placeholder: 'Enter a URL', class: "flex-grow rounded" %>
    <!--required: true (enforce the existence at view level)-->
    <%= form.button "Shorten", class: "px-3 py-2 bg-gray-100 rounded" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link) do %>
  <%= turbo_stream_from link %>

  <div class="grid grid-cols-8 items-center py-4">
    <%#= link_to link.to_param, link %>
    <div class="col-span-5">
      <%= link_to view_path(link), target: :_blank, data: {turbo: false}, class: "no-underline" do %>
        <%= favicon_image_tag link.domain, class: "inline-block m-0" %>
        <%= link.title || link.url %>
        <%= tag.div truncate link.description, class: "text-xs text-gray-700" %>
        <svg xmlns="https://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 inline-block">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
        </svg>
      <% end %>
    </div>

    <div class="col-span-2 text-center text-xs">
      <%= link_to pluralize(link.views_count, "view"), link, class: "px-2 py-1.5 rounded bg-gray-100 no-underline"%>
    </div>

    <div class="text-center text-xs">
      <%= button_tag "Copy", class: "font-medium px-2 py-1.5 rounded bg-gray-100 no-underline", data: {controller: "clipboard", clipboard_text: view_url(link)} %>
    </div>

    </div>
<% end %>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= render partial: "form", locals: {link: @link} %>

<div class="mt-4 flex gap-2 items-center">
  <%= link_to 'Cancel', @link %>
  or
  <%= button_to 'Delete', @link, method: :delete, data: {turbo_confirm: "Are you sure ?"} %>
</div>

app/views/links/index.html.erb
<h1>URL Shortener</h1>

<%= render partial: 'form', locals: {link: @link} %>

<div id="links" class="mt-8 flex flex-col gap-4 divide-y divide-gray-100">
  <%= render @links %>  <!-- render the instance variable @links in links_controller.rb -->
</div>

app/views/links/show.html.erb
<div class="flex justify-between items-center text-xs">
  <%= link_to "← Back to all links", root_path, class: "no-underline text-xs px-3 py-2 rounded bg-gray-100" %>
  <div class="flex items-center gap-4">
    <%= tag.div pluralize(@link.views_count, "view") %>
    <%= button_tag "Copy", class: "font-medium px-2 py-1.5 rounded bg-gray-100 no-underline", data: {controller: "clipboard", clipboard_text: view_url(@link)} %>
    <%= link_to "Edit", edit_link_path(@link), class: "px-2 py-1.5 rounded bg-gray-100 no-underline" %>
  </div>
</div>

<h1 class="mt-4"><%= @link.url %></h1>
<%= tag.div @link.description %>
  <%= link_to view_path(@link), target: :_blank, data: {turbo: false}, class: "text-xs px-2 py-1.5 rounded bg-gray-100 no-underline" do %>
    <%= favicon_image_tag @link.domain, class: "inline-block" %>
    <%= truncate @link.url %>
    <svg xmlns="https://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 inline-block">
      <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
    </svg>
  <% end %>
<%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true).count %>